=pod

=head1 NAME

xdg-sound-whereis - locate sound files for an event identifier

=head1 SYNOPSIS

B< xdg-sound-whereis> [I<OPTIONS>] [--] I<EVENTID> [...]
 B<xdg-sound-whereis> [I<OPTIONS>] {B<-l>|B<--list>}
 B<xdg-sound-whereis> {B<-h>|B<--help>}
 B<xdg-sound-whereis> {B<-V>|B<--version>}
 B<xdg-sound-whereis> {B<-C>|B<--copying>}

=head1 DESCRIPTION

B<xdg-sound-whereis> locates the sound file and sound data for the
specified event identifiers.  The supplied names are first stripped of
leading path-name components and any (single) trailing extension of the
form F<.ext> (for example: F<.oga>).  B<xdg-sound-whereis> then attempts
to locate the desired sound file in the standard Linux places, and in
the places specified by C<XDG_DATA_DIRS> and C<XDG_DATA_HOME>.

=head1 ARGUMENTS

The program accepts the following arguments:

=over

=item I<EVENTID>

Specifies the event identifier of an XDG sound to locate.  The event
identifier can be one of the following:

=over

=item 1.

the name of an event identifier without any sound-file-specific
extension (e.g.  F<.oga>) suffix (e.g. F<system-bootup>); the name may
contain a C</> if it is specified relative to a user or system
application directory, in which case it must not start with a C</> or
C<.>.

=item 2.

the name of an event identifier with a sound-file-specific extension
(e.g.  F<.oga>) suffix (e.g. F<system-bootup.oga>); the same
restrictions as (1), above, apply; or,

=item 3.

the full path (absolute or relative) and filename of a sound file (e.g.
F</usr/share/sounds/freedesktop/stereo/system-bootup.oga>); the full
path must contain at least one C</> and start with either a C</> or a
C<.>.

=back

Provide a non-option event identifier argument is mandatory unless a
non-default command option is specified.

=back

=head1 OPTIONS

The options that are detailed below are recognized by
B<xdg-sound-which>.  B<xdg-sound-which> uses L<getopt_long_only(3)>, so
unambiguous abbreviations of long options and long options with a single
dash are also supported.

=head2 COMMAND OPTIONS

The default is to match the I<EVENTID> and provide output.  When any of
the following options are specified, the command mode changes:

=over

=item B<-l>, B<--list>

Instead of searching for an event identifier, print the directories that
will be searched for sound themes and sound files in the order in which
they will be searched.

Output list of effective lookup paths that B<xdg-sound-whereis> is using.

=item B<-h>, B<--help>

Prints usage information to standard output and exits.

=item B<-V>, B<--version>

Prints detailed version information and exits.

=item B<-C>, B<--copying>

Prints detailed copying permissions and exits.

=back

=head2 GENERAL OPTIONS

The following general options are recognized:

=over

=item B<-a>, B<--all>

Print all matching sound files, not just the first.

=item B<-o>, B<--skip-dot>

Skip directories in C<XDG_DATA_DIRS> that start with a dot.

=item B<-t>, B<--skip-tilde>

Skip directories in C<XDG_DATA_DIRS> that start with a tilde and entries
that reside in C<XDG_DATA_HOME>.

=item B<-O>, B<--show-dot>

If a directory starts with a dot and a matching event sound file was
found for that path, then print C<./eventid.ext> rather than the full
path.

=item B<-T>, B<--show-tilde>

Output a tilde when a directory matches the C<HOME> directory.

=item B<-N>, B<--theme> I<THEME>

Specify the sound theme to use when looking up event identifiers.
Defaults to the current GTK sound theme.

=item B<-P>, B<--profile> I<PROFILE>

Specify the output profile to use when looking up event identifiers.
Defaults, and falls back, to C<stereo>.

=back

=head1 EXAMPLES

Following are some examples of invocation and output:

=head1 ENVIRONMENT

The following environment variables are examined by B<xdg-sound-whereis>:

=over

=item B<HOME>

Used by B<xdg-sound-whereis> to determine the user's home directory.

=item B<XDG_DATA_HOME>

Used by B<xdg-sound-whereis> to determine the user's XDG data directory.
This defaults to F<$HOME/.local/share>.  The F<sounds> sub-directory
under this directory is the first searched to locate event sound files.
See the XDG Sound Theme file specification for more information.

=item B<XDG_DATA_DIRS>

Used by B<xdg-sound-whereis> to determine the system XDG data directories.
This defaults to F</usr/local/share:/usr/share>.  The F<sounds>
sub-directory under these directories are searched in order to locate
event sound files.  See the XDG Sound Theme file specification for more
information.

=back

=head1 BUGS

B<xdg-sound-whereis> has no known bugs.
Pleas report bugs to the source code repository at
L<https://github.com/bbidulock/xdg-sound/issues>.

=head1 SEE ALSO

L<getopt_long_only(3)>,
L<xdg-play(1)>,
L<xdg-sound-list(1)>,
L<xdg-sound-which(1)>.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
