=pod

=head1 NAME

xdg-sound-which - show the full path of XDG sound entries

=head1 SYNOPSIS

B< xdg-sound-which> [I<OPTIONS>] [--] I<EVENTID> [...]
 B<xdg-sound-which> [I<OPTIONS>] {B<-l>|B<--list>}
 B<xdg-sound-which> {B<-h>|B<--help>}
 B<xdg-sound-which> {B<-V>|B<--version>}
 B<xdg-sound-which> {B<-C>|B<--copying>}

=head1 DESCRIPTION

B<xdg-sound-which> takes one or more arguments.  For each of its
arguments, it prints to standard output the full path of the sound file
that would have been played when this argument had been supplied to
L<xdg-play(1)>.  It does this by searching for a sound entry in the
appropriate sub-directories of the C<XDG_DATA_DIRS> and C<XDG_DATA_HOME>
environment variables using the same algorithms as L<xdg-play(1)>.

=head1 ARGUMENTS

The program accepts the following arguments:

=over

=item I<EVENTID>

Specifies the event identifier of an XDG sound to locate.  The event
identifier can be one of the following:

=over

=item 1.

the name of an event identifier without any sound-file-specific
extension (e.g.  F<.oga>) suffix (e.g. F<system-bootup>); the name may
contain a C</> if it is specified relative to a user or system
application directory, in which case it must not start with a C</> or
C<.>.

=item 2.

the name of an event identifier with a sound-file-specific extension
(e.g.  F<.oga>) suffix (e.g. F<system-bootup.oga>); the same
restrictions as (1), above, apply; or,

=item 3.

the full path (absolute or relative) and filename of a sound file (e.g.
F</usr/share/sounds/freedesktop/stereo/system-bootup.oga>); the full
path must contain at least one C</> and start with either a C</> or a
C<.>.

=back

Provide a non-option event identifier argument is mandatory unless a
non-default command option is specified.

=back

=head1 OPTIONS

The options that are detailed below are recognized by
B<xdg-sound-which>.  B<xdg-sound-which> uses L<getopt_long_only(3)>, so
unambiguous abbreviations of long options and long options with a single
dash are also supported.

=head2 COMMAND OPTIONS

The default is to match the I<EVENTID> and provide output.  When any of
the following options are specified, the command mode changes:

=over

=item [B<-w>, B<--which>]

When specified, or no command option is specified, print which sound
file that would be played for the given event identifiers, by
L<xdg-play(1)>.

=item B<-l>, B<--list>

Instead of searching an event identifier, print the directories that
will be searched for sound themes and sound files in the order in which
they will be searched.

Output list of effective lookup paths that B<xdg-sound-which> is using.

=item B<-h>, B<--help>

Prints usage information to standard output and exits.

=item B<-V>, B<--version>

Prints detailed version information and exits.

=item B<-C>, B<--copying>

Prints detailed copying permissions and exits.

=back

=head2 SELECTION OPTIONS

Selection options help determine which sound theme events to output.
The following selection options are recognized:

=over

=item B<-S>, B<--standard>

When used with the B<--show> command mode, list all standard XDG event
names found in the freedesktop.org XDG sound naming specification,
instead of the available ones.

=item B<-a>, B<--all>

Normally only the first matching event sound file for a given event
identifier is printed or played: this option prints or plays all
matching sound files, not just the first.
This is similar to L<which(1)>'s B<--all> option.

=item B<-o>, B<--skip-dot>

Skip directories in C<XDG_DATA_DIRS> and C<XDG_DATA_HOME> that start
with a dot.  This has the effect of suppressing relative paths.
This is similar to L<which(1)>'s B<--skip-dot> option.

=item B<-t>, B<--skip-tilde>

Skip directories in C<XDG_DATA_DIRS> that start with a tilde (that is,
the user's C<HOME> directory) and entries that reside in
C<XDG_DATA_HOME>.  This has the effect of suppressing user overrides to
the sound theme.
This is similar to L<which(1)>'s B<--skip-tilde> option.

=item B<-N>, B<--theme> I<THEME>

Specify the sound theme name to use when looking up event identifiers.
Defaults to the user's current GTK 2.0 then GTK 3.0 sound theme.
Defaults, and falls back, to C<freedesktop> when no GTK 2.0 sound theme
name is available.

=item B<-P>, B<--profile> I<PROFILE>

Specify the output profile to use when looking up event identifiers.
Defaults, and falls back, to C<stereo>.

=item B<-c>, B<--context> I<CONTEXT>

Specifies the event context to use when looking up or listing event
identifiers.  Only sub-directories that have this context or no
specified context will be searched or listed.  Event identifiers that
exist in a different context (or standard context) will be skipped.

Therefore, specifying a I<CONTEXT> option and then specifying an
I<EVENTID> argument that is a standard event that corresponds to a
different context is not terribly useful.

When used with B<--standard>, only the standard event identifiers that
correspond to the specified context will be used.  Standard event
identifiers that correspond to a different context will be skipped.
When used with B<--standard>, I<CONTEXT> may be one of the following:

=over

=item C<Alert>, C<Alerts> Directory: I<alert>

Sounds to alert the user of an action or event that may have a major
impact on the system or their current use, such as C<dialog-error>.

=item C<Notification>, C<Notifications> Directory: I<notification>

Sounds to notify the user that the system, or their current use, has
changed state in some way, e.g: new email arriving, new non-critical
updates available.

=item C<Support>, C<Actions> Directory: I<action>

Sounds that give the user feedback on their actions.  Sounds on taking a
screenshot, for example.

=item C<Support>, C<Input Feedback> Directory: I<action>

Sounds that give the user feedback on their input.  Sounds on window
opening or closing, for example.

=item C<Game> Directory: I<game>

Sounds used for games.

=back

=item B<-u>, B<--user> I<USER>

Pretend to be user, I<USER>, instead of the current user when following
the XDG sound theme procedures; however, use the same effective
C<XDG_DATA_DIRS> and C<XDG_DATA_HOME> settings.  See also, L</USAGE>,
below.

=item B<--xdg-data-home> I<PATHSPEC>

Set the C<XDG_DATA_HOME> environment variable to I<PATHSPEC> before
examining it or performing actions.  Useful only with the B<--user>
option.
Any tildes (C<~>) found in I<PATHSPEC> will be replaced with the
effective user's home directory.

=item B<--xdg-data-dirs> I<PATHSPEC>

Set the C<XDG_DATA_DIRS> environment variable to I<PATHSPEC> before
examining it or performing actions.  Useful only with the B<--user>
option.
Any tildes (C<~>) found in I<PATHSPEC> will be replaced with the
effective user's home directory.

=back

=head2 OUTPUT OPTIONS

The following output options are recognized:

=over

=item B<-O>, B<--show-dot>

If a directory starts with a dot and a matching event sound file was
found for that path, then print C<./eventid.ext> rather than the full
path.

=item B<-T>, B<--show-tilde>

Output a tilde when a directory matches the C<HOME> directory.

=item B<-r>, B<--headers>

When listing output, event identifier headers are not normally printed:
this option, adds event identifier headers to any output.

=item B<-d>, B<--deref>

Paths to sound files are normally printed even when they are symbolic
links: this option causes symbolic links to be dereferenced before
printing the path.
This option is not useful when used in conjunction with the B<--play>
option.

=item B<-p>, B<--play>

Normally output prints the names of the event identifiers and sound
files on standard output: this option causes the events to also be
played.  To only play the event identifiers, use in conjunction with the
B<--quiet> option.

=item B<-n>, B<--noplay>

Normally when event sounds are played, audio option is generated: this
option suppresses the generation of audio output and only prints the
localized sound data associated with the event sound file.  When no
F<.sound> sound data files exist for the selected sounds, an internal
"C" locale string is printed instead.
This option is only useful in conjunction with the B<--play> option
(specified or implied).

=back

=head2 GENERAL OPTIONS

The following general options are recognized:

=over

=item B<-q>, B<--quiet>

Suppress normal output.  This has the same effect as the combination of
B<--verbose>=I<0> and B<--debug>=I<0> and is intended on suppressing
output to standard out.  The exit status and printing of diagnostics to
standard error are unaffected.

=item B<-v>, B<--verbose> [I<LEVEL>]

Print diagnostic information to standard error during operation.  This
option can be repeated to increase the verbosity of output.  The default
level is 1.

=item B<-D>, B<--debug> [I<LEVEL>]

Prints debugging information to standard error during operation.  This
option can be repeated to increase the debugging level.  The default
level is 0.

=back

=head1 USAGE

=head2 USER OPTION

Using the B<--user> option to mimic the behaviour of another user may
require super-user privileges to be able access files in the user's home
directory.  Because the intention is to use the current user's
C<XDG_DATA_DIRS> and C<XDG_DATA_HOME> environment variables with the
user's home directory substituted, and L<sudo(1)> does not pass
C<XDG_DATA_DIRS> and C<XDG_DATA_HOME> environment variables, it is
necessary to use a L<bash(1)> command, such as follows, to invoke
B<xdg-sound-which>:

The B<--user> option is ineffective when used with the B<--skip-tilde>
option.

=head1 BEHAVIOUR

=head1 EXAMPLES

Following are some examples of invocation and output:

 $> xdg-sound-which system-bootup
 /usr/share/sounds/freedesktop/stereo/system-bootup.oga

 $> xdg-sound-which -a -N unexicon -P 5.1 --show-tilde system-bootup
 ~/.local/share/sounds/unexicon/stereo/system-bootup.oga
 /usr/share/sounds/freedesktop/stereo/system-bootup.oga

=head1 ENVIRONMENT

The following environment variables are examined by B<xdg-sound-which>:

=over

=item B<HOME>

Used by B<xdg-sound-which> to determine the user's home directory.

=item B<XDG_DATA_HOME>

Used by B<xdg-sound-which> to determine the user's XDG data directory.
This defaults to F<$HOME/.local/share>.  The F<sounds> sub-directory
under this directory is the first searched to locate event sound files.
See the XDG Sound Theme file specification for more information.

When the B<--user> option is specified and the current effective user is
root, this environment variable is ignored.  The default value of
C<XDG_DATA_HOME> for the specified user will be used unless the
B<--xdg-data-home> option is also specified.

=item B<XDG_DATA_DIRS>

Used by B<xdg-sound-which> to determine the system XDG data directories.
This defaults to F</usr/local/share:/usr/share>.  The F<sounds>
sub-directory under these directories are searched in order to locate
event sound files.  See the XDG Sound Theme file specification for more
information.

When the B<--user> option is specified and the current effective user is
root, this environment variable is ignored.  The default value of
C<XDG_DATA_DIRS> for the specified user will be used unless the
B<--xdg-data-dirs> option is also specified.

=back

=head1 BUGS

B<xdg-sound-which> has no known bugs.
Pleas report bugs to the source code repository at
L<https://github.com/bbidulock/xdg-sound/issues>.

=head1 SEE ALSO

L<getopt_long_only(3)>,
L<xdg-play(1)>,
L<xdg-sound-list(1)>,
L<xdg-sound-whereis(1)>.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
